"""init"""

revision = "a65d3b2f1b3f"
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_key', sa.String(length=64), nullable=False),
    sa.Column('section_name', sa.String(length=128), nullable=False),
    sa.Column('service_name', sa.String(length=512), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('attributes_json', sa.Text(), nullable=False),
    sa.Column('source_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_key', 'section_name', 'row_order', name='uq_bank_services_sheet_section_row')
    )
    op.create_index(op.f('ix_bank_services_section_name'), 'bank_services', ['section_name'], unique=False)
    op.create_index(op.f('ix_bank_services_service_name'), 'bank_services', ['service_name'], unique=False)
    op.create_index(op.f('ix_bank_services_sheet_key'), 'bank_services', ['sheet_key'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('landmarks', sa.Text(), nullable=True),
    sa.Column('metro', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('hours', sa.String(length=255), nullable=True),
    sa.Column('weekend', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=64), nullable=True),
    sa.Column('mfo', sa.String(length=64), nullable=True),
    sa.Column('postal_index', sa.String(length=32), nullable=True),
    sa.Column('uzcard_accounts', sa.Text(), nullable=True),
    sa.Column('humo_accounts', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_district'), 'branches', ['district'], unique=False)
    op.create_index(op.f('ix_branches_region'), 'branches', ['region'], unique=False)
    op.create_table('credit_product_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=128), nullable=False),
    sa.Column('service_name', sa.String(length=512), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('min_age_text', sa.String(length=128), nullable=True),
    sa.Column('purpose_text', sa.Text(), nullable=True),
    sa.Column('amount_text', sa.Text(), nullable=True),
    sa.Column('amount_min', sa.BigInteger(), nullable=True),
    sa.Column('amount_max', sa.BigInteger(), nullable=True),
    sa.Column('term_text', sa.String(length=255), nullable=True),
    sa.Column('term_min_months', sa.Integer(), nullable=True),
    sa.Column('term_max_months', sa.Integer(), nullable=True),
    sa.Column('downpayment_text', sa.String(length=255), nullable=True),
    sa.Column('downpayment_min_pct', sa.Float(), nullable=True),
    sa.Column('downpayment_max_pct', sa.Float(), nullable=True),
    sa.Column('income_type', sa.String(length=32), nullable=True),
    sa.Column('rate_text', sa.Text(), nullable=True),
    sa.Column('rate_condition_text', sa.Text(), nullable=True),
    sa.Column('rate_min_pct', sa.Float(), nullable=True),
    sa.Column('rate_max_pct', sa.Float(), nullable=True),
    sa.Column('collateral_text', sa.Text(), nullable=True),
    sa.Column('source_path', sa.String(length=255), nullable=True),
    sa.Column('source_row_order', sa.Integer(), nullable=False),
    sa.Column('rate_order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_name', 'source_row_order', 'rate_order', 'income_type', name='uq_credit_product_offers_row_rate')
    )
    op.create_index(op.f('ix_credit_product_offers_income_type'), 'credit_product_offers', ['income_type'], unique=False)
    op.create_index(op.f('ix_credit_product_offers_section_name'), 'credit_product_offers', ['section_name'], unique=False)
    op.create_index(op.f('ix_credit_product_offers_service_name'), 'credit_product_offers', ['service_name'], unique=False)
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_ru', sa.Text(), nullable=False),
    sa.Column('answer_ru', sa.Text(), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=True),
    sa.Column('answer_en', sa.Text(), nullable=True),
    sa.Column('question_uz', sa.Text(), nullable=True),
    sa.Column('answer_uz', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='sessionstatus', native_enum=False), server_default='active', nullable=False),
    sa.Column('human_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('human_mode_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_operator_id', sa.BigInteger(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('closed_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('agent_model', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('faq')
    op.drop_index(op.f('ix_credit_product_offers_service_name'), table_name='credit_product_offers')
    op.drop_index(op.f('ix_credit_product_offers_section_name'), table_name='credit_product_offers')
    op.drop_index(op.f('ix_credit_product_offers_income_type'), table_name='credit_product_offers')
    op.drop_table('credit_product_offers')
    op.drop_index(op.f('ix_branches_region'), table_name='branches')
    op.drop_index(op.f('ix_branches_district'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_bank_services_sheet_key'), table_name='bank_services')
    op.drop_index(op.f('ix_bank_services_service_name'), table_name='bank_services')
    op.drop_index(op.f('ix_bank_services_section_name'), table_name='bank_services')
    op.drop_table('bank_services')
    # ### end Alembic commands ###
